---
title: "Final data and methods"
output: html_document
date: "2024-11-03"
bibliography: references.bib
author: "Lucan Bovens"
---

```{=html}
<style>
div {
text-align: justify}
</style>
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

----

# Data

The data used originates from collaboration data of researchers from the sociology departments of three Dutch universities. This selection is part of a larger dataset examining collaborations between researchers of sociology and political science departments across universities where these fields are present. This broader dataset, which is the first step of the collection for this paper, was collected through web scraping. Based on the staff lists on the university websites, the names, departments and positions were collected per researcher. Researchers' Google Scholar IDs were then added to the dataset. This data was collected for two different years, specifically 2022 and 2024, allowing for the observation of changes over time. \
    The next step involved the use of OpenAlex, an online catalog that tracks authors and their published articles. OpenAlex also records co-authors for each publication, making it possible, through web scraping, to identify which authors collaborate. The authors’ works were then integrated into the existing dataset, resulting in a dataset comprising both personal information of the authors and their published works. \
    Finally, I chose to include only sociologists from the Radboud University, the University of Groningen, and Utrecht University. This choice was made for three reasons: the first was to have a sufficiently large sample for the analyses, and the second was due to the fact that, in the Netherlands, collaboration often occurs between the same departments across different universities, meaning that isolated cases are less likely. The final reason was that sociologists share the same academic context regardless of university; they generally publish in the same journals and hold the same standards, which I expect leads to comparable prestige across departments. In contrast, comparing different departments might introduce more discrepancies in terms of context and perception of prestige. \
    These waves are based on the publication years of the articles rather than the data collection timeline. The first wave covers 2015-2018, and the second wave spans 2019-2023, with each wave representing a four-year period. As mentioned, the data makes it possible to determine whether authors have collaborated on a publication. These waves essentially represent two collaboration networks, where a tie represents authors who have published together. The networks are directed using a "first-author" approach, allowing for analysis of who sends and receives ties. The "first" form assumes that the first author listed on a paper initiates a tie to the other authors. \
    Before discussing the variables used, I would like to address the ethics surrounding web scraping and the principle of Open Science. As this study may reveal "hidden" dynamics within a social network that are not typically captured with standard data, this raises questions regarding ethical aspects. All web-scraped data is publicly available online for anyone to access. No private information was collected or used in the data analysis. To ensure transparency and replicability of the study, the method for data collection is documented in both this lab journal and my GitHub repository. \

## Dependent variable
    Since the aim of this study is to investigate whether prestige matters in choosing whom to work together with, it is this formation of collaboration ties between scholars that is the dependent variable. This variable is then represented by an adjacency matrix for both waves, with the first wave representing the publication network of 2015-2018 and the second wave of 2019-2023. For the adjacency matrices, a score of 1 indicates a tie between two scholars, meaning they have collaborated on a publication, while a 0 means they have not collaborated. Since it is expected that the first author initiated the collaboration to work on the paper, the networks are directed accordingly, as discussed above. It is expected that these ties, once established, are not removed, since that would mean the paper had to be withdrawn after publication. \

## Independent variable
    The independent variable in this paper is the prestige of an author. As mentioned earlier, prestige is a complex concept, which can encompass many aspects. It is also potentially subjective, with some valuing certain elements or traits over others. However, some objective ways to measure prestige do exist, with the h-index being especially notable. The h-index is a metric used to represent both the impact and productivity of an author. It measures prestige more accurately than the total number of publications, as the latter does not indicate impact. Additionally, the h-index “weeds out” the possible influence of a select few highly-cited articles. The h-index namely measures an author’s prestige by calculating the number of publications that have been cited at least as many times as the total number of their publications. As explained by the creator of the h-index, " A scientist has index h if h of his or her Np papers have at least h citations each and the other (Np - h) papers have ≤h citations each." (Hirsch, 2005). \
    OpenAlex keeps track of the h-index for all authors, and as such, I webscraped the h-index of all scholars in the dataset. One limitation of the h-index, however, is that it does not consider a scholar’s career length. Following an approach by Alonso, Cabrerizo, Herrera-Viedma & Herrera (2009), I created a new prestige index by dividing the h-index by the logarithm of the scholar's career age of each author. The career age data was gathered using a method by Koen Lucas and career age was then calculated by subtracting the year of a scholar’s first publication from 2024. For scholars with a career age of 0, I changed this to 1 to avoid dividing by zero. By dividing the h-index by career age, an author with more years in academia does not necessarily have a much higher h-index than scholars who had not yet had a lengthy career. The logarithmic scaling then smoots the effect of career length. As such, junior scholars are not punished by their short career lengths, while senior scholars are not disproportionately punished for having longer career lengths.  \

## Control variable
    Next to prestige, it is possible that other factors play a role in determining who to work with, and one of the biggest such factors is gender. Therefore, I have added gender as a control variable. For this, I used a gender scraper based on the Dutch Nederlandse Voornamenbank (the Dutch names database, MeertensInstituut, n.d.). This gender scraper was developed by Niels Vullings. The gender scraper gave the percentage chance that a name is either male or female. For simplicity’s sake, I created a dichotomized variable, where each name with a 50% or greater likelihood of being female was assigned as female, and less than 50% was assigned as male. \

## Analytical strategy
    To answer the research questions and test the hypotheses, I will perform two kinds of analysis. The first is a more descriptive approach and will be used to get an overview of the network’s structural characteristics. The second analysis has a more analytical nature, which will be used to get a better understanding of which dynamics may lead to collaboration among scholars. As such, with this two-folded approach I will be able to answer both the descriptive as well as the explanatory research questions. \
    Hypotheses 2 and 3 will be analyzed with the use of network visualization. In these visualizations, the nodes represent the scholars, while the edges represent whether a co-authorship tie exists. The direction of the edges, following the assumption made above, indicates which scholar has initiated the collaboration. While the visualization of a network does not yet provide concrete figures about what effects exist, mapping the network does make it possible to see the structure of the network and thus allows the identifying of clusters and the possible existence of hubs around certain scholars. Some key network statistics, such as density, degree, transitivity, and a clustering coefficient, will be used to apply some figures to the plots. Furthermore, I will look at both a dyad census and a triad census for the network. Finally, it is possible to check for changes over time. As such, I will compare the network statistics of wave 1 and wave 2 to check whether a change in the degree of, for example, clustering has taken place over time, which can signal an evolving role of prestige. \
  For hypotheses 1 and 4, regarding the influence of prestige on tie formation, I will use RSiena models, using the R package with the same name. RSiena simulates network evolution through a Stochastic Actor Oriented Model (SAOM). Through this SAOM, it is assumed that actors make several mini-steps actors to form ties, where each time just one randomly selected actor is allowed to make such a mini-step. This one actor then ‘decides’ whether they would like to maintain, create or abandon just one tie at a time, and evaluates the network. Afterwards, the next randomly selected actor goes through the same process. These decisions are then influenced by both the variables added to the model, such as prestige and gender, as well as through several structural network variables, such as transitivity, degree, and reciprocity. Finally, by simulating multiple of these mini-steps, which is needed due to the non-deterministic sequential nature of the mini-steps, it is estimated how the variables in the model affect how ties form within the network. \
    As mentioned, several structural network effects, will be added to the models as well. These structural effects can be seen as independent variables, functioning as network statistics and refer to the tendencies of the actors within the network to form specific types of ties, such as closing triads. These structural effects occur regardless of individual attributes.  \

## Model estimation
    The RSiena analysis will actually consist of multiple models. At first, the analysis will start with a null model. This null model will only include the density (outdegree) and reciprocity structural effects, as this is a standard setting within RSiena. Model 1 will contain some structural effects for the analysis, such as indegree and transitive triples. Then, Model 2 adds the covariate effect of prestige to the existing model. In Model 3 the covariate effect of gender will be added, to serve as a control variable. Model 4 replaces the prestige similarity of model 2 with alter prestige, and excludes gender again. Model 5 then adds gender as control variable again. Finally, goodness of fit tests will be applied to the five models. \
    
 
-------------


