---
title: "Final introduction"
output: html_document
date: "2024-11-03"
bibliography: references.bib
author: "Lucan Bovens"
---

```{=html}
<style>
div {
text-align: justify}
</style>
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

----

# Introduction

Collaboration among scholars in the academic world has become increasingly more common over the years. Where formerly lone academic wolves used to be the standard, they have now become a rarity. A more collaborative workspace has become the norm, with scholars now forming collaborative networks through co-authorship and the average number of co-authors steadily increasing (Choueiry, 2022; Fanelli & Vincent Larivière, 2016; Horta, Feng & Santos, 2022; Thelwall & Maflahi, 2022). Advantages of such scientific collaboration include the access to diverse expertise, sharing of resources, increased funding opportunities and enhanced research productivity (Cheong & Corbitt, 2009; de Miranda Grochocki & Cabello, 2023). Junior scholars or PhD students often seek out senior scholars to aid them with their research, leading to the latter frequently becoming co-authors on the resulting papers. On the other hand, senior scholars may offer their services to aspiring juniors, acting as their mentor. \ 
    
    However, collaboration dynamics are not always so straightforward. The academic world is, controversially, a meritocracy based on status. In the academic context, the number of citations a scholar accumulates, and the number of papers published can both serve as indicators of their success, or in other words, their prestige or status. While it is seldom openly discussed, there exists the possibility that it is this prestige, rather than the actual content of publications, that is the leading determinant when choosing a collaboration partner. As such, citations may be the merit on which researchers decide whether or not to collaborate with another researcher (e.g. Hâncean & Perc, 2016; Shen, Xie, Li & Cheng, 2021). \
  Following from that, there exists the possibility that scholars with a higher number of citations might then predominantly prefer to collaborate with others who have a similar number of citations, reflecting what is referred to as the prestige effect, elitism in collaboration, or the ‘birds of a feather’ phenomenon (Hâncean & Perc, 2016; McPherson, Smith-Lovin & Cook, 2001). The main reason to collaborate with peers at their own level would be to retain a sense of elitism or achieved prestige, maintaining their status within the academic hierarchy (Hâncean & Perc, 2016). \
  Given these prestige dynamics, four patterns of collaboration within these networks can be identified; 1. Junior scholars may seek out senior scholars; 2. Seniors may seek out junior scholars; 3. Seniors may seek collaboration with their peers; 4. Junior scholars may seek out their peers. Seeing how there are various possibilities of establishing networks, this further raises the question about how exactly social networks in academia come to be and evolve over time, and how exactly the status of a scholar matters in that regard. A social network perspective is crucial in this context, as it has become clear that individuals may base their behavior on the existence of others within their own network (Tolsma & Hofstra, 2022). Individuals are then not independent, as is commonly assumed within the social sciences, but rather they are _inter_-dependent. Individuals form relationships with others, and these relationships may develop into networks. For example, when scholars with a similar amount of citations tend to stick together, a high degree of homophily would exist within their network (McPherson, Smith-Lovin & Cook, 2001), and clustering in the social network may appear. As such, a social network perspective is necessary for understanding structures of academic collaboration networks. \
  Following from the above, in this paper I will thus investigate how the prestige of a scholar plays a part in how collaboration networks within an academic context come to be. As mentioned, there are various possibilities, with scholars potentially having different preferences regarding the status another scholar has. The four different patterns of collaboration also give way to different kinds of network structures. If prestige indeed is deemed to be the key determinant of collaboration preference, a highly centralized network dominated by a few prestigious scholars could emerge, following the idea of a scale-free network (Kim, 2019). If a higher prestige is not sought after, a more evenly distributed network could be observed. This leads to two, descriptive, research questions:  \ 

  *RQ1: To what extent do clusters around high-prestige scholars exist within a collaboration network?*\ 

  *RQ2: To what extent do we find separate clusters of scholars with similar levels of prestige?*\ 

This descriptive question helps identifying clusters with the network and provides a foundational view of the network structure, but it is still not sure then what role the prestige of a scholar plays exactly, and what mechanisms can explain the structure of the network. The question is then whether the prestige of a scholar is a cause of the network that exists. As such, the second, explanatory, research question is:

  *RQ3: To what extent does scholar prestige play a part in forming collaboration ties within co-publication networks?*

If prestige does indeed play a role in forming the collaboration network of scholars within the departments at the Radboud Universities, it remains important to assess the dynamics of this mechanism. Looking at the four different patterns of collaboration, the following two research questions can be raised:

  *RQ4a: Do high-prestige scholars prefer to collaborate with peers of similar prestige, or are they more likely to collaborate with lower-prestige scholars?*\ 

  *RQ4b: Do lower-prestige scholars predominantly initiate co-publication ties with higher-prestige scholars, or do they tend to collaborate with peers of similar prestige?*\ 

With these research questions, it is the aim to check whether it is, in terms of prestige, either homophily or hierarchical patterns that form the structure of the network. In the next section, I will elaborate on these potential mechanism and discuss how the theory can explain the dynamics underlying the network structure.  \ 

-------------

