---
title: "Final conclusion"
output: html_document
date: "2024-11-03"
bibliography: references.bib
author: "Lucan Bovens"
---

```{=html}
<style>
div {
text-align: justify}
</style>
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

----

# Conclusion

The aim of this study was to explore how prestige plays a role in collaboration dynamics within academic networks, with a specific focus on the co-publication network of scholars within the Dutch sociology departments of the Radboud University, the University of Groningen and Utrecht University. The prestige of the scholars was based on the h-index, which is a measure to assess the impact and productivity a scholar has by looking at the total number of citations and total number of publications. The data used in this study were mostly derived from webscraped data using the OpenAlex online database. The data was collected for years, resulting in two waves of publication networks; from 2015-2018 and 2019-2023. \
    The hypotheses were tested using two methods. First, two hypotheses were tested by analyzing network visualizations and estimating the degree centrality. The other hypotheses were tested by utilizing the RSiena package, which uses a Stochastic Actor-Oriented Model (Ripley et al., 2024). As the method of network visualization had to be performed before the RSiena models, hypotheses 2 and 3 were tested first. \
    Hypothesis 2 stated that clusters of highly prestigious scholars would exist within the collaboration networks, assuming that scholars with a high prestige would often work together and would collaborate less with scholars who have a lower prestige. From the network visualization, however, there was no support found for this hypothesis. A mix of different levels of prestige was mostly observed in the visualizations, with highly prestigious scholars beging scattered around the network. \
    Hypothesis 3 was in some respect conflicting to hypothesis 2, stating that highly prestigious scholars occupy central positions within the collaboration networks, assuming that they serve as mentors and are thus linked to many scholars with lower prestige. The network visualizations shows that highly prestigious scholars indeed received plenty of ties from scholars with a lower level of prestige. To further test whether hypothesis 3 would hold, degree centrality was estimated. A Spearman correlation between degree centrality and prestige showed that prestige is indeed associated receiving more ties. As such, evidence for hypothesis 3 was found. \
    Hypotheses 1 and 4 were tested using RSiena. Hypothesis 1 suggests that scholars would prefer to collaborate with scholars who have a similar prestige rather than with scholars who have a different level of prestige. The effect of the prestige parameter was not significant, indicating that scholars do not seem to consider similarity in prestige when finding co-authors, which means hypothesis 1 is rejected. On the other hand, hypothesis 4 suggests that scholars are more likely to collaborate with highly prestigious scholars. The effect of alter prestige was significantly positive, both without and with gender added as a control variable. Thus, it appears that scholars tend to prefer collaborating with those who have higher levels of prestige. Hypothesis 4 was then accepted. \
    This study had a few limitations. When webscraping from OpenAlex, there is always a risk that the data available may contain inaccuracies, potentially causing issues due to the external data. Additionally, the data was collected in a short time frame, leading to a restriction of the waves that can be used. This short time frame then limits the ability to observe more trends over time. Lastly, by using career age as a factor in calculating the prestige index, this meant that career age could not be added as a control variable to prevent multicollinearity issues. \
    Overall, this study has highlighted the role of prestige in shaping collaboration networks and has shown that prestige does matter in the formation of co-publication ties with other scholars. Scholars seem to prefer to work with highly prestigious scholars. Future research could build on these insights by expanding the observation period and by adding more covariates to the networks.



-------------
