---
title: "Final RSiena GOF"
output: html_document
date: "2024-10-31"
bibliography: references.bib
author: "Lucan Bovens"
---

```{=html}
<style>
div {
text-align: justify}
</style>
```
  
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
----

# RSiena goodness of fit (GOF)

Lastly, goodness of fit tests were performed for the five models that were estimated. These goodness of fit (GOF) tests are important for RSiena, since the RSiena packages uses simulation, which is prone to errors. In a best case scenario, the simulation would match the changes observed in the network perfectly. However, in reality this is not always a perfect match. As such, goodness of fit tests checks if the models accurately reflect the patterns observed in the network. As the research questions and the hypotheses focus on the role scholars with a high prestige play on the the structure of networks and whether they receive ties based on their prestige, I decided to use the indegree distribution as the metric to base the goodness of fit tests on. \
    For some reason that I do not know, the goodness of fits for all five models are very bad. It may be the case that not enough variables are added to the models, since I have only included the prestige index and gender. It may also be the case that something went wrong with the data preparation, but I would not know where. Possibly due to the 'final prep' part where I had to do some work-arounds after the data did not run anymore. Due to time constraints I have not had the time to find out what exactly causes the goodness of fits to have these values. It would take too much time to run all the data again. As such, it must be said that based on these goodness of fits, it should be noted that the results of this study need to be interpreted with care. 
  
----
  
## Prep

Cleaning the workspace

```{r}
rm(list=ls())
```

Defining the functions

```{r}
fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

fsave <- function(x, file = NULL, location = "./data/processed/") {
    ifelse(!dir.exists("data"), dir.create("data"), FALSE)
    ifelse(!dir.exists("data/processed"), dir.create("data/processed"), FALSE)
    if (is.null(file))
        file = deparse(substitute(x))
    totalname <- paste(location, file, ".rda", sep = "")
    save(x, file = totalname)
}


fload <- function(filename) {
    load(filename)
    get(ls()[ls() != "filename"])
}

fshowdf <- function(x, ...) {
    knitr::kable(x, digits = 2, "html", ...) %>%
        kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
        kableExtra::scroll_box(width = "100%", height = "300px")
}
```

Loading packages

```{r}
packages <- c("tidyverse", "scholar", "openalexR", "rvest", "jsonlite", "RSiena", "RSelenium", "rvest", "lavaan", "xml2", "kableExtra", "devtools", "igraph", "network", "sna", "ggraph", "visNetwork", "threejs", "networkD3", "RsienaTwoStep", "dplyr")


fpackage.check(packages)
```

```{r}
# make yourself known to openAlex
options(openalexR.mailto = "lucan.bovens@home.nl")
```

```{r}
# Load final prepared data
df_ego <- fload("./data/processed/df_ego_final.rda")
socdata <- fload("./data/processed/socdata_final.rda")
dfworks <- fload("./data/processed/df_works_final.rda")
```

## Model 1

```{r}
ans1 <- fload("./data/processed/ans1.rda")
```

```{r}
GOFM1 <- sienaGOF(ans1, IndegreeDistribution, verbose = FALSE, join = TRUE, varName = "net")

plot(GOFM1, main = "GOF indegrees model 1")

```

## Model 2

```{r}
ans2 <- fload("./data/processed/ans2.rda")
```

```{r}

GOFM2 <- sienaGOF(ans2, IndegreeDistribution, verbose = FALSE, join = TRUE, varName = "net")

plot(GOFM2, main = "GOF indegrees model 2")

```

## Model 3

```{r}
ans3 <- fload("./data/processed/ans3.rda")
```

```{r}

GOFM3 <- sienaGOF(ans3, IndegreeDistribution, verbose = FALSE, join = TRUE, varName = "net")

plot(GOFM3, main = "GOF indegrees model 3")

```

## Model 4

```{r}
ans4 <- fload("./data/processed/ans4.rda")
```

```{r}

GOFM4 <- sienaGOF(ans4, IndegreeDistribution, verbose = FALSE, join = TRUE, varName = "net")

plot(GOFM4, main = "GOF indegrees model 4")

```

## Model 5

```{r}
ans5 <- fload("./data/processed/ans5.rda")
```

```{r}

GOFM5 <- sienaGOF(ans5, IndegreeDistribution, verbose = FALSE, join = TRUE, varName = "net")

plot(GOFM5, main = "GOF indegrees model 5")

```

```{r}
?sienaGOF
```

