---
title: "Journal 1"
#bibliography: references.bib
author: "Lucan Bovens"
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

----
  
This is the example page of my `r colorize("lab journal", "red")`. On this example page I try out different *fonts*, text sizes, `r colorize ("colours", "blue")` , et cetera. 
This example page will (and has to) be removed for the final version of my lab journal.
  

----


```{r}
print("Hello Lab Journal")
```



