---
title: "Week 4: Chapter 9 assignment"
output: html_document
date: "2024-09-25"
bibliography: references.bib
author: "Lucan Bovens"
---
  
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
----
  
# Week 4 -  Chapter 9 assignment
  
----
  
```{r}
# start with clean workspace
rm(list = ls())

require(RSelenium)
require(RSiena)
require(scholar)
require(tidyverse)
require(openalexR)
require(jsonlite)
require(lavaan)
require(xml2)
require(rvest)
require(kableExtra)
require(devtools)
require(igraph)
require(network)
require(sna)
require(ggraph)
require(visNetwork)
require(threejs)
require(networkD3)
#require(ndtv)
```

```{r}
??Zachary
g <- make_graph("Zachary")
plot(g)
```

```{r}
gmat <- as_adjacency_matrix(g, type = "both", sparse = FALSE)
(gmat)
```

```{r}
# number of nodes
vcount(g)
# number of edges
ecount(g)
```

```{r}
igraph::degree(g)
#hist(table(degree(g)), xlab='indegree', main= 'Histogram of indegree')
?dyad_census
```

```{r}
# be aware that directed graphs are considered as undirected. but g is undirected.
igraph::transitivity(g, type = c("localundirected"), isolates = c("NaN", "zero"))
```

```{r}
igraph::betweenness(g, directed = FALSE)
```

```{r}
g_dir <- igraph::as.directed(g, mode = "mutual")
igraph::dyad_census(g_dir)
```

```{r}
igraph::triad_census(g_dir)
# I will use sna because it shows the names of the triads as well.
sna::triad.census(gmat)
?triad_census
plot(g_dir)
detach("package:ndtv", unload = TRUE)
unloadNamespace("sna")  #I will detach this package again, otherwise it will interfere with all kind of functions from igraph, and my students will hate me for that.
```

```{r}
igraph::transitivity(g, type = "global")
sna::gtrans(gmat)

triad_g <- data.frame(sna::triad.census(gmat))

transitivity_g <- (3 * triad_g$X300)/(triad_g$X201 + 3 * triad_g$X300)
transitivity_g
```

```{r}
# changing V
V(g)$size = igraph::betweenness(g, normalized = T, directed = FALSE) * 60 + 10  #after some trial and error
plot(g, mode = "undirected")
```

```{r}
set.seed(2345)
l <- layout_with_mds(g)  #https://igraph.org/r/doc/layout_with_mds.html
plot(g, layout = l)
```

```{r}
l  #let us take a look at the coordinates
l[1, 1] <- 4
l[34, 1] <- -3.5
plot(g, layout = l)
```

```{r}
plot(g, layout = l, margin = c(0, 0, 0, 0))
legend(x = -2, y = -0.5, c("Note: the position of nodes 1 and 34 have been set by Jochem Tolsma \n for visualisation purposes only and do not reflect network properties."),
    bty = "n", cex = 0.8)
```



