---
title: "Week 2: Assignment Class"
output: html_document
date: "2024-09-10"
bibliography: references.bib
author: "Lucan Bovens"
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
----

# Week 2 -  Assignment (4x4 matrix and triads)

----

```{r}
require(igraph)
#require(sna)
require(RSiena)
```

```{r}
emptymatrix <- matrix(c(0,0,0,0,
                0,0,0,0,
                0,0,0,0,
                0,0,0,0), nrow = 4, ncol = 4)

print(emptymatrix)

graph1 <- graph_from_adjacency_matrix(emptymatrix, mode = c("directed"))
emptymatrix_graph <- triad_census(graph1)
emptymatrix_graph
```

```{r}
# insert a tie

onetie <- matrix(c(0,0,0,0,
                1,0,0,0,
                0,0,0,0,
                0,0,0,0), nrow = 4, ncol = 4)

print(onetie)

onetiegraph1 <- graph_from_adjacency_matrix(onetie, mode = c("directed"))
onetie_graph <- triad_census(onetiegraph1)
onetie_graph
```

```{r}
library(RSiena)
library(sna)
library(igraph)

?s501
s501
dim(s501)

s501chunk <- s501[1:10, 1:10]
s501chunk

?triad_census
?RSiena

graphs501chunk <- graph_from_adjacency_matrix(s501chunk, mode = c("directed"))
triad_census(graphs501chunk)

plot(graphs501chunk)

igraph::degree(graphs501chunk)

View(s501chunk)
```

```{r}
densitys501 <- edge_density(graphs501chunk)
densitys501
```

```{r}
degrees501 <- igraph::degree(graphs501chunk, mode = "out")
degrees501

degrees501norm <- igraph::degree(graphs501chunk, mode = "out", normalized = TRUE)
degrees501norm

degrees501normform <- (degrees501 - min(degrees501))/(max(degrees501)) - min(degrees501)
degrees501normform
```

